plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/ClassLength:
  Max: 125
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 26
  Exclude:
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Enabled: true
  Max: 55
  Exclude:
    - "test/**/*"

Metrics/PerceivedComplexity:
  Max: 10
